### ISSUE TITLE
Format local time configurably

### ISSUE THREAD

**Issue by peerst** [grisp/dgram_logger#2]
Timestamps are currently not sent to influxdb, we rely on the time of the server.

This should be configurable since we might have wrong or unreliable time on embedded systems and that is *one* use case of this lib

**Comment by Laymer** [comment]
I have a quick question about this just to make sure, would it be useful to have a way to configure whether the time should be send or not, for example : 

`[Level, Tags, Io_list]` or `[Level, Tags, Io_list, Time]` when it is known in advance if a system has correct time or not ? 

Or would the enhancement be to be able to adjust the time on the embedded system when possible at runtime?
