### ISSUE TITLE
Start the gen_server from handler_added instead the other way round

### ISSUE THREAD

**Issue by peerst** [grisp/dgram_logger#8]
And store the pid in the handler, also shut down the gen_server if the handler is removed.

- [X] Handlers should be added by users and not by the application
- [x] Start and shutdown a separate process for each handler

**Comment by eproxus** [comment]
Should be started here:
https://github.com/grisp/dgram_logger/blob/master/src/dgram_logger.erl#L20
Then socket can be requested and put into `Config`.

**Comment by eproxus** [comment]
Handlers are no longer added as from 9476009726ceb401049f12c1d3e5801cebbb303b.

**Comment by eproxus** [comment]
Separate process and socket started for each handler added in 1067301a97f7dccc7d22c2aabb04d517adbda146.
